codecov:
  require_ci_to_pass: yes
  allow_coverage_offsets: false
  strict_yaml_branch: main
  max_report_age: 24
  disable_default_path_fixes: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error
        only_pulls: false
    patch: off
    changes: off

comment:
  layout: "files"
  behavior: default
  require_changes: false

github_checks:
  annotations: true

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - name_prefix: project-
        type: project
        target: auto
        threshold: 1%
  individual_flags:
    - name: python311
      paths:
        - src/
      statuses:
        - type: project
          target: auto
          threshold: 1%

ignore:
  - "tests/"
  - "setup.py"
  - "*/__init__.py" 