codecov:
  token: 5b27097b-4819-43fc-b77e-41167d796f76
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
  
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "tests/**/*"
  - "setup.py"

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true 